server:
  port: 8081


# for Postgresql database connection.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobweb
    username: postgres
    password: root@123
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect


# for Actuator use...
# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"
#   endpoint:
#     health:
#       showDetails: always
#   info:
#     env:
#       enabled: true

# set details to "/info"
info:
  app:
    name: JobWeb
    description: JobWep application using monolithic-architecture, build by Sajee...
    version: 1.0.0

